# Generated by Django 5.2.4 on 2025-07-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name": "Меню", "verbose_name_plural": "Меню"},
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
            },
        ),
    ]
